name: Malaria Api
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build docker image
        run: |
          docker build -t malaria-api -f ml/api/Dockerfile .

      - name: Start container
        run: |
          docker run -d -p 8000:8000 --name malaria-api-container malaria-api

      - name: Wait for API
        run: |
          sleep 10
          until curl -f http://localhost:8000/health; do
            sleep 5
            done
      - name: Run tests
        run: |
          curl -f http://localhost:8000/health
          curl -f http://localhost:8000/model-info
          echo "API работает - проект готов"
          # cd desktop-app
          # gradle test --tests "*ApiHealthCheckTest*"
